apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.argovue.io
spec:
  group: argovue.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: services
    singular: service
    kind: Service
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            image:
              type: string
            sharedVolume:
              type: string
            privateVolumeSize:
              type: string
