apiVersion: argovue.io/v1
kind: Service
metadata:
  name: dash
  labels:
    oidc.argovue.io/group: authors
spec:
  input:
  - name: env1
    caption: Variable one
  - name: env2
    caption: Variable two
  helmRelease:
    chart:
      git: https://github.com/jamhed/argovue.git
      path: helm/simple
    values:
      image: jamhed/dash:0.1.1
      port: 8000
      privateVolumeSize: 1M
