apiVersion: argovue.io/v1
kind: Service
metadata:
  name: argovue-filebrowser
spec:
  input: []
  helmRelease:
    chart:
      git: https://github.com/jamhed/argovue.git
      path: helm/filebrowser
