apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objects.kubevue.io
spec:
  group: kubevue.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: objects
    singular: object
    kind: Object
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            group:
              type: string
            version:
              type: string
            name:
              type: string
            namespace:
              type: string
