apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple.fullname" . }}
  labels:
    oidc.argovue.io/id: {{ .Values.argovue.owner }}
    {{- include "simple.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple.selectorLabels" . | nindent 4 }}
