/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "argovue/client/clientset/versioned/scheme"
	"time"

	v1 "argovue/apis/argovue.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceTypesGetter has a method to return a ServiceTypeInterface.
// A group's client should implement this interface.
type ServiceTypesGetter interface {
	ServiceTypes(namespace string) ServiceTypeInterface
}

// ServiceTypeInterface has methods to work with ServiceType resources.
type ServiceTypeInterface interface {
	Create(*v1.ServiceType) (*v1.ServiceType, error)
	Update(*v1.ServiceType) (*v1.ServiceType, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ServiceType, error)
	List(opts metav1.ListOptions) (*v1.ServiceTypeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceType, err error)
	ServiceTypeExpansion
}

// serviceTypes implements ServiceTypeInterface
type serviceTypes struct {
	client rest.Interface
	ns     string
}

// newServiceTypes returns a ServiceTypes
func newServiceTypes(c *KubevueV1Client, namespace string) *serviceTypes {
	return &serviceTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceType, and returns the corresponding serviceType object, and an error if there is any.
func (c *serviceTypes) Get(name string, options metav1.GetOptions) (result *v1.ServiceType, err error) {
	result = &v1.ServiceType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicetypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceTypes that match those selectors.
func (c *serviceTypes) List(opts metav1.ListOptions) (result *v1.ServiceTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ServiceTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicetypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceTypes.
func (c *serviceTypes) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicetypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceType and creates it.  Returns the server's representation of the serviceType, and an error, if there is any.
func (c *serviceTypes) Create(serviceType *v1.ServiceType) (result *v1.ServiceType, err error) {
	result = &v1.ServiceType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicetypes").
		Body(serviceType).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceType and updates it. Returns the server's representation of the serviceType, and an error, if there is any.
func (c *serviceTypes) Update(serviceType *v1.ServiceType) (result *v1.ServiceType, err error) {
	result = &v1.ServiceType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicetypes").
		Name(serviceType.Name).
		Body(serviceType).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceType and deletes it. Returns an error if one occurs.
func (c *serviceTypes) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicetypes").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceTypes) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicetypes").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceType.
func (c *serviceTypes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceType, err error) {
	result = &v1.ServiceType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicetypes").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
