apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple.fullname" . }}
  labels:
    {{- include "simple.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "simple.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        oidc.argovue.io/id: {{ .Values.argovue.owner }}
        {{- include "simple.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
          protocol: TCP
        volumeMounts:
        {{- if .Values.privateVolumeSize }}
        - mountPath: /mnt/private
          name: private
        {{- end }}
        env:
        - name: BASE_URL
          value: {{ .Values.argovue.baseurl }}
      volumes:
      {{- if .Values.privateVolumeSize }}
      - name: private
        persistentVolumeClaim:
          claimName: {{ template "simple.fullname" . }}
      {{- end }}
