apiVersion: argovue.io/v1
kind: Service
metadata:
  name: filebrowser
  labels:
    oidc.argovue.io/group: authors
spec:
  input: []
  helmRelease:
    chart:
      git: https://github.com/jamhed/argovue.git
      path: helm/filebrowser
