apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevue.fullname" . }}
  labels:
    {{- include "kubevue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubevue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubevue.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubevue.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OIDC_CLIENT_ID
              value: {{ .Values.kubevue.oidcClientId }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.kubevue.oidcClientSecret }}
            - name: OIDC_PROVIDER
              value: {{ .Values.kubevue.oidcProvider }}
            - name: OIDC_REDIRECT_URL
              value: {{ .Values.kubevue.oidcRedirectUrl }}
            - name: OIDC_SCOPE
              value: {{ .Values.kubevue.oidcScope }}
            - name: UI_ROOT_URL
              value: {{ .Values.kubevue.rootUrl }}
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
