replicaCount: 1

image:
  repository: jamhed/argovue
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: tpp-venafi-issuer
  hosts:
  - argovue.prod.nv.ak8s.mckinsey.com

argovue:
  verbose: debug
  oidcClientId: argovue
  oidcClientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
  oidcProvider: http://argovue.prod.nv.ak8s.mckinsey.com/dex
  oidcRedirectUrl: http://argovue.prod.nv.ak8s.mckinsey.com/callback
  oidcScope: groups
  uiRootUrl: http://argovue.prod.nv.ak8s.mckinsey.com/ui/#/

dex:
  enabled: true
  logger:
    level: debug
  issuer: http://argovue.prod.nv.ak8s.mckinsey.com/dex
  connectors:
  - type: mockCallback
    id: mock
    name: Example
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - id: argovue
    redirectURIs:
    - http://argovue.prod.nv.ak8s.mckinsey.com/callback
    name: 'ArgoVue'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
