replicaCount: 1

image:
  repository: jamhed/argovue
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

argovue:
  verbose: debug
  oidcClientId: argovue
  oidcClientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
  oidcProvider: http://localhost:8080/dex
  oidcRedirectURL: http://localhost:8080/callback
  oidcScope: groups
  uiRoot: /ui/#/

dex:
  enabled: true
  logger:
    level: debug
  issuer: http://localhost:8080/dex
  connectors:
  - type: mockCallback
    id: mock
    name: Example
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - id: argovue
    redirectURIs:
    - http://localhost:8080/callback
    name: 'ArgoVue'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  enablePasswordDB: true
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
