apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
  labels:
    oidc.argovue.io/group: authors
    oidc.argovue.io/id: 726f6d616e5f67616c656576406d636b696e7365792e636f6d
spec:
  entrypoint: dag
  volumeClaimTemplates:
  - metadata:
      name: work
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Mi  
  templates:
  - name: alpine
    retryStrategy:
      limit: 1
    inputs:
      parameters:
      - name: script
    container:
      image: alpine
      command: [sh, -c]
      args: ["{{inputs.parameters.script}}"]
      volumeMounts:
      - name: work
        mountPath: /work
  - name: dag
    dag:
      tasks:
      - name: a
        template: alpine
        arguments:
          parameters: [{name: script, value: "touch /work/a ; sleep 10; echo a"}]
      - name: b
        template: alpine
        arguments:
          parameters: [{name: script, value: "for i in $(seq 1 100); do echo b$i; sleep 5; done"}]
      - name: c
        template: alpine
        dependencies: [a, b]
        arguments:
          parameters: [{name: script, value: "touch /work/c ; sleep 10; echo c"}]
