name: publish
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        name: jamhed/kubevue
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build_args: VERSION=${{ steps.get_version.outputs.VERSION }}
        auto_tag: true
