apiVersion: v1
kind: Pod
metadata:
  name: argovue
  namespace: argovue
  labels:
    app: argovue
spec:
  containers:
    - name: main
      image: argovue
      command: ["sh", "-c"]
      args: ["./argovue -verbose=debug"]
      env:
        - name: OIDC_CLIENT_ID
          value: argovue
        - name: OIDC_CLIENT_SECRET
          value: ZXhhbXBsZS1hcHAtc2VjcmV0
        - name: OIDC_PROVIDER
          value: http://localhost:8080/dex
        - name: OIDC_REDIRECT_URL
          value: http://localhost:8080/callback
        - name: OIDC_SCOPES
          value: email groups
        - name: UI_ROOT_URL
          value: http://localhost:8081/ui/#/
        - name: K8S_NAMESPACE
          value: default
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
