apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: argovue
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
  - resourceType: pod
    resourceName: argovue
    namespace: argovue
    port: 8080
    localPort: 8080
