apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: kubevue
deploy:
  kubectl:
    manifests:
      - k8s-*
portForward:
  - resourceType: pod
    resourceName: kubevue
    namespace: kubevue
    port: 8080
    localPort: 8080
